      
export const AUTH_LOGGING_IN = 'LOGGING_IN';
export const AUTH_LOGGED_IN = 'LOGGED_IN';
export const AUTH_ERR_LOG_IN = 'ERR_LOG_IN';
export const AUTH_LOGOUT = 'LOGOUT';
export const AUTH_CLEAR_LOGIN_ERROR_MESSAGE = 'CLEAR_LOGIN_ERROR_MESSAGE';